# Generated by Django 4.0.6 on 2022-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminHub', '0004_alter_sesiones_admins_id_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones_Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'NOTICIA'), ('2', 'LABORAL'), ('3', 'VIDEO')], default='1', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminHub.admins')),
            ],
        ),
    ]
