# Generated by Django 4.0.6 on 2022-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicacionAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones_admins',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones_admins',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
