# Generated by Django 4.0.6 on 2022-07-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicacionAdmin', '0002_alter_publicaciones_admins_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones_admins',
            name='titulo',
            field=models.TextField(default='Publicacion<django.db.models.fields.AutoField>', max_length=60),
        ),
    ]
