# Generated by Django 4.0.6 on 2022-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicacionAdmin', '0005_alter_publicaciones_admins_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones_admins',
            name='titulo',
            field=models.TextField(default='Publicacion', max_length=100),
        ),
    ]
