# Generated by Django 4.0.6 on 2022-07-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicacionAdmin', '0006_alter_publicaciones_admins_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones_Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(default='Publicacion', max_length=100)),
                ('subtitulo', models.TextField(default='Subtitulo', max_length=100)),
                ('tipo', models.CharField(choices=[('1', 'ANUNCIO'), ('2', 'AVISO')], default='1', max_length=3)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('tags', models.TextField(blank=True, max_length=100)),
                ('ruta_img', models.TextField(blank=True, max_length=100)),
                ('referencias', models.TextField(blank=True, max_length=100)),
                ('hipervinculo', models.TextField(blank=True, max_length=100)),
                ('id_publicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PublicacionAdmin.publicaciones_admins')),
            ],
        ),
    ]
