# Generated by Django 4.0.6 on 2022-07-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
