# Generated by Django 4.0.6 on 2022-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0002_delete_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_programa', models.TextField(max_length=60)),
                ('clave_programa', models.IntegerField()),
                ('plan', models.IntegerField()),
                ('expediente', models.IntegerField()),
                ('nombre', models.TextField(max_length=60)),
                ('status', models.TextField(max_length=20)),
                ('cred_pasante', models.IntegerField()),
                ('cred_aprob', models.IntegerField()),
                ('prom_kdxs', models.FloatField()),
                ('prom_periodo', models.FloatField()),
                ('mat_aprob', models.IntegerField()),
                ('materias_acreditadas', models.TextField(blank=True, max_length=255)),
                ('materias_segunda_inscr', models.TextField(blank=True, max_length=255)),
                ('materias_tercera_inscr', models.TextField(blank=True, max_length=255)),
                ('materias_reprobadas', models.TextField(blank=True, max_length=255)),
                ('materias_bajas_voluntarias', models.TextField(blank=True, max_length=255)),
                ('cred_inscr', models.IntegerField()),
                ('nivel_y_ciclo_ingles', models.TextField(max_length=10)),
                ('correo', models.TextField(max_length=25)),
                ('cred_cult', models.FloatField()),
                ('cred_dep', models.FloatField()),
                ('practica_profesional_estatus_y_ciclo', models.TextField(blank=True, max_length=20)),
                ('serviciosocialmateriaestatus_ciclo', models.TextField(blank=True, max_length=20)),
                ('estatusproyectoserviciosocial_cicloregistro', models.TextField(blank=True, max_length=20)),
                ('egel_testimonio', models.TextField(blank=True, max_length=60)),
                ('inscrito', models.BooleanField()),
            ],
        ),
    ]
