# Generated by Django 4.0.6 on 2022-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='materias_inscritas',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
