# Generated by Django 4.0.6 on 2022-07-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0008_alumnos_materias_inscritas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
