# Generated by Django 4.0.6 on 2022-07-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='inscrito',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
