# Generated by Django 4.0.6 on 2022-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
