# Generated by Django 4.0.6 on 2022-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminHub', '0003_sesiones_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones_admins',
            name='id_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminHub.admins'),
        ),
    ]
