# Generated by Django 4.0.5 on 2022-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('AnuncioId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('MateriaId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('PlanEstudioId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PracticasProfesionales',
            fields=[
                ('PracticasProfesionalesId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('ServicioSocialId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
